version: "3"
services:
  nextjs-docker-image:
    container_name: climatetrax_dev
    build:
      context: .
      dockerfile: Dockerfile
    image: nextjs-docker-image:latest
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app

