apiVersion: skaffold/v4beta4
kind: Config
metadata:
  name: climatetrax-docker-k-s
build:
  artifacts:
    - image: nextjs-docker-image
      docker:
        dockerfile: Dockerfile
  tagPolicy:
    sha256: {}
manifests:
  rawYaml:
    - kubernetes/nextjs-app-deployment.yaml
    - kubernetes/nextjs-app-service.yaml
