name: Playwright Tests

on: [push]

concurrency:
  group: CT-caller-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  call-workflow-trivy-scan:
    uses: button-inc/button-shared-gh-actions/.github/workflows/test-code-playwright.yml@develop
