name: Scan ClimateTrax FE

on: [push]

concurrency:
  group: caller-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
    call-workflow-trivy-scan:
      uses: button-inc/button-shared-gh-actions/.github/workflows/scan-code-trivy.yml@develop
      
    call-workflow-husky-scan:
      uses: button-inc/button-shared-gh-actions/.github/workflows/scan-code-husky.yml@develop

    gitleaks: 
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
          with:
            fetch-depth: 0
        - uses: gitleaks/gitleaks-action@v2
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE}}
            GITLEAKS_NOTIFY_USER_LIST: "@shon-button,@YaokunLin"

      
    