# Tests that rely on the committed code, without needing the docker images to be built
name: Scan ClimateTrax FE

on: [push]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
    trivy-scan-code:
        runs-on: ubuntu-latest
        timeout-minutes: 60
        steps:
          - name: Checkout code
            uses: actions/checkout@v3
          - name: Cache Scan Dependencies
            uses: actions/cache@v2
            with:
              path: ~/.cache/trivy
              key: ${{ github.workflow }}-${{ github.run_id }}
              restore-keys: trivy-
          - name: Run Trivy vulnerability scanner in repo mode
            uses: aquasecurity/trivy-action@master
            with:
              scan-type: fs
              format: sarif
              output: trivy-results.sarif
              exit-code: "0"
              ignore-unfixed: false
              severity: UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL
              timeout: 10m0s
          - name: Upload Trivy scan results as artifact 
           # can't use the Advanced Security feature for the result uploading
           # as it is only for a public repo or a private repo within GitHub Enterprise 
            uses: actions/upload-artifact@v2
            with:
              name: trivy-results
              path: trivy-results.sarif

    install-dev-tools:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Set up Node.js
          uses: actions/setup-node@v2
          with:
            node-version: '18' # Change this to the Node.js version your project supports
        - run: yarn install --frozen-lockfile --check-files
          working-directory: ./app

    husky-checks:
      needs: install-dev-tools
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v2
          with:
            node-version: '18'
        - uses: actions/cache@v2
          with:
            path: |
              ~/.npm
            key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
            restore-keys: |
              ${{ runner.os }}-node-
        - run: yarn install # Ensuring all dev dependencies including Husky are installed
          working-directory: ./app
        - run: npm run lint
          working-directory: ./app
