# Tests that rely on the committed code, without needing the docker images to be built
name: Scan ClimateTrax FE

on: [push]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
    trivy-scan-code:
        runs-on: ubuntu-latest
        timeout-minutes: 60
        steps:
          - name: Checkout code
            uses: actions/checkout@v3
          - name: Cache Scan Dependencies
            uses: actions/cache@v2
            with:
              path: ~/.cache/trivy
              key: ${{ github.workflow }}-${{ github.run_id }}
              restore-keys: trivy-
          - name: Run Trivy vulnerability scanner in repo mode
            uses: aquasecurity/trivy-action@master
            with:
              scan-type: fs
              format: sarif
              output: trivy-results.sarif
              exit-code: "0"
              ignore-unfixed: false
              severity: UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL
              timeout: 10m0s
          - name: Upload Trivy scan results as artifact 
           # can't use the Advanced Security feature for the result uploading
           # as it is only for a public repo or a private repo within GitHub Enterprise 
            uses: actions/upload-artifact@v2
            with:
              name: trivy-results
              path: trivy-results.sarif

    # install-dev-tools:
    #   runs-on: ubuntu-latest
    #   steps:
    #     - uses: actions/checkout@v2
    #     - name: dev env setup
    #       uses: ./.github/actions/dev-env-setup
    #     - run: make install_dev_tools
    #     - run: make stop_pg # cleanly stop the database, otherwise it will complain in the subsequent jobs
    #     - run: yarn install --frozen-lockfile --check-files
    #       working-directory: ./app              

    pre-commit:
      #needs: install-dev-tools
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: dev env setup
          uses: ./.github/actions/dev-env-setup
        - name: set pre-commit cache directory
          run: |
            echo "PRE_COMMIT_HOME=$GITHUB_WORKSPACE/.pre-commit-cache" >> $GITHUB_ENV
        - name: set PY
          run: echo "PY=$(python -VV | sha256sum | cut -d' ' -f1)" >> $GITHUB_ENV
        - name: create commitlint COMMIT_EDITMSG if not exists
          run: |
            if test -f ".git/COMMIT_EDITMSG"; then
                echo "COMMIT_EDITMSG EXISTS, skipping"
            else
                touch .git/COMMIT_EDITMSG
            fi
        - uses: actions/cache@v2
          with:
            path: |
              ./.pre-commit-cache
            key: pre-commit-${{ env.PY }}-${{ hashFiles('.pre-commit-config.yaml') }}
        - run: pre-commit run --all-files --color=always --show-diff-on-failure    
    # cannot use
    # only open to public repo or private one under GH enterprise          
    # codeql-scan:
    #   name: codeql-scan
    #   runs-on: ubuntu-latest
    #   permissions:
    #     actions: read
    #     contents: read
    #     security-events: write
    #   strategy:
    #     fail-fast: false
    #     matrix:
    #       language: ["javascript"]
    #       os: ["linux"]
    #   steps:
    #     - name: Checkout repository
    #       uses: actions/checkout@v2
    #     - name: Initialize CodeQL
    #       uses: github/codeql-action/init@v2
    #       with:
    #         languages: ${{ matrix.language }}
    #     - name: Autobuild
    #       uses: github/codeql-action/autobuild@v2
    #     - name: Perform CodeQL Analysis
    #       uses: github/codeql-action/analyze@v2
